#!/usr/bin/env node

const unhal = require('./index')
const fs = require('fs')

try {
  const stdin = fs.readFileSync("/dev/stdin", "utf-8")
  const input_data = JSON.parse(stdin)
  const output_data = unhal(input_data)
  const json = JSON.stringify(output_data)
  console.log(json)
} catch (err) {
  console.error(err.message)
  process.exit(1)
}
